trigger:
- main

pool:
  name: default

variables:
  # Define a variable to reference the service connection
  SERVICE_CONNECTION_NAME: 'EC2_Connection'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Installing PHP 7.4 and dependencies"
        sudo apt-get update
        sudo apt-get install -y php7.4 php7.4-cli php7.4-fpm php7.4-mysql php7.4-mbstring php7.4-xml php7.4-json php7.4-curl
      displayName: 'Install PHP 7.4 and Extensions'
      
    - script: |
        echo "Installing Composer"
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version
      displayName: 'Install Composer'
      
    - script: |
        echo "Running Composer install"
        composer install --no-interaction --prefer-dist
      displayName: 'Composer Install'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: $(SERVICE_CONNECTION_NAME)
        runOptions: 'commands'
        commands: |
          echo "Deploying to EC2"
          cd /var/www/html || exit 1
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          git pull origin main || exit 1
          composer install --no-dev || exit 1
          sudo systemctl restart php7.4-fpm || exit 1
      displayName: 'Deploy to EC2'