trigger:
- main

pool:
  name: default

variables:
  # Define variables for EC2 deployment
  EC2_HOST: '43.205.173.158'
  EC2_USER: 'ubuntu'
  EC2_KEY: '$(EC2_SSH_PRIVATE_KEY)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - script: |
        echo "Installing PHP dependencies"
        sudo apt-get update
        sudo apt-get install -y php php-cli php-fpm php-mysql php-pdo php-mbstring php-xml php-json
        echo "Running composer install"
        composer install
      displayName: 'Install PHP Dependencies'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - script: |
        echo "Deploying to EC2"
        ssh -i $(EC2_KEY) -o StrictHostKeyChecking=no $(EC2_USER)@$(EC2_HOST) << 'EOF'
        cd /path/to/your/application
        git pull origin main
        composer install --no-dev
        sudo systemctl restart php7.4-fpm
        EOF
      displayName: 'Deploy to EC2'
