trigger:
- main # Trigger builds on changes to the main branch

pool:
  name: default

variables:
  phpVersion: '7.4'
  buildConfiguration: 'Release'
  artifactName: 'yii-app'
  buildOutput: '$(Pipeline.Workspace)/$(artifactName).zip'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y php$(phpVersion) php-cli php-mbstring php-xml unzip
    php -v
  displayName: 'Install PHP and Dependencies'

- script: |
    composer install --no-dev --optimize-autoloader
  displayName: 'Install PHP dependencies'

- script: |
    zip -r $(buildOutput) . -x "*.git*" -x "*.git/***"
  displayName: 'Package application'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: $(artifactName)
    pathToPublish: $(buildOutput)
  displayName: 'Publish Build Artifacts'

