trigger:
- main

pool:
  name: default

variables:
  # Define variables for EC2 deployment
  EC2_HOST: '43.205.173.158'
  EC2_USER: 'ubuntu'
  EC2_KEY: '$(EC2_SSH_PRIVATE_KEY)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Installing PHP dependencies"
        sudo apt-get update
        sudo apt-get install -y php7.4 php7.4-cli php7.4-fpm php7.4-mysql php7.4-mbstring php7.4-xml php7.4-json
        echo "Running composer install"
        composer install
      displayName: 'Install PHP Dependencies'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        echo "Deploying to EC2"
        ssh -i $(EC2_KEY) -o StrictHostKeyChecking=no $(EC2_USER)@$(EC2_HOST) << 'EOF'
        cd /var/www/html
        git pull origin main
        composer install --no-dev
        sudo systemctl restart php7.4-fpm
        EOF
      displayName: 'Deploy to EC2'
