trigger:
- main

pool:
  name: default

variables:
  # Define variables for EC2 deployment
  EC2_HOST: '43.205.173.158'
  EC2_USER: 'ubuntu'
  EC2_KEY: '$(EC2_SSH_PRIVATE_KEY)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Updating package list and installing PHP 8.0 and dependencies"
        sudo apt-get update
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get update
        sudo apt-get install -y php8.0 php8.0-cli php8.0-fpm php8.0-mysql php8.0-mbstring php8.0-xml php8.0-json php8.0-curl
      displayName: 'Install PHP 8.0 and Extensions'
      
    - script: |
        echo "Setting PHP 8.0 as the default version"
        sudo update-alternatives --set php /usr/bin/php8.0
        sudo update-alternatives --set php-config /usr/bin/php-config8.0
        sudo update-alternatives --set phpize /usr/bin/phpize8.0
        sudo update-alternatives --set php-fpm /usr/sbin/php-fpm8.0
      displayName: 'Configure PHP Alternatives'

    - script: |
        echo "Installing Composer"
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version
      displayName: 'Install Composer'
      
    - script: |
        echo "Running Composer install"
        composer install --no-interaction --prefer-dist
      displayName: 'Composer Install'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        echo "Deploying to EC2"
        ssh -i $(EC2_KEY) -o StrictHostKeyChecking=no $(EC2_USER)@$(EC2_HOST) << 'EOF'
        cd /var/www/html
        git pull origin main
        composer install --no-dev
        sudo systemctl restart php8.0-fpm
        EOF
      displayName: 'Deploy to EC2'
