trigger:
- main

pool:
  name: default

variables:
  # Define variables for EC2 deployment
  EC2_HOST: '43.205.173.158'
  EC2_USER: 'ubuntu'
  EC2_KEY: '$(EC2_SSH_PRIVATE_KEY)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Installing PHP 7.4 and dependencies"
        sudo apt-get update
        sudo apt-get install -y php7.4 php7.4-cli php7.4-fpm php7.4-mysql php7.4-mbstring php7.4-xml php7.4-json php7.4-curl
      displayName: 'Install PHP 7.4 and Extensions'
      
    - script: |
        echo "Installing Composer"
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version
      displayName: 'Install Composer'
      
    - script: |
        echo "Running Composer install"
        composer install --no-interaction --prefer-dist
      displayName: 'Composer Install'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        echo "Deploying to EC2"
        ssh -i $(EC2_KEY) -o StrictHostKeyChecking=no $(EC2_USER)@$(EC2_HOST) << 'EOF'
        cd /var/www/html
        git pull origin main
        composer install --no-dev
        sudo systemctl restart php7.4-fpm
        EOF
      displayName: 'Deploy to EC2'
